<MyLayout>
    BoxLayout:
        orientation:'vertical'
        size:root.width,root.height

        Label:
            id:lblTexto
            text:"0% Progress"
        ProgressBar:
            id:my_progress_bar
            value:0
            min:0
            max:100
            pos_hint:{'x':.1}
            size_hint_x:.8

        Button:
            text:"Press"
            on_press:root.btnClick()