<MyLayout>

    BoxLayout:
        orientation:'vertical'
        size:root.width, root.height
        padding:50
        spacing:20

        Label:
            id:lblTexto
            text: "Hello World"
            font_size:32

        Button:
            text: "Press"
            font_size:32
            size_hint:.5, .5
            pos_hint:{"center_x":0.5}

            on_release:root.animate_it(self)